sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 272697
  redis:
    host: localhost
    port: 6379
    password: 272697
    database: 10
  alioss:
    access-key-id: LTAI5tHCBfpHymGJcq8QZa6k
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-secret: UMS5WSe5DRFaMpQbCWBBWKAMP2Yd6u
    bucket-name: zhuzhuweb11
  wechat:
    appid: wx388cbd50e9a3ca27
    secret: e7270cf07d9ef73061cd65ad77987139
